---
destination : _site
lsi         : false
highlighter : rouge
permalink   : /:year/:month/:title
paginate    : 3
markdown    : kramdown
include     : [".htaccess", ".well-known"]
exclude	    : ["rsync-site.sh", ".git", ".gitignore", "Gemfile", "Gemfile.lock", "script", "vendor", "tmp"]
url         : "https://www.devinberg.com/"

author:
    name : Devin R. Berg
    email : devinberg@gmail.com
    github : devinberg
    twitter : devinberg

kramdown:
    parse_block_html: true

gems:
  - jekyll-seo-tag
